from typing import Protocol
from src.shared.domain.models_device_token import DeviceToken


class DeviceTokenPort(Protocol):
    def save(self, user_id: str, token: str) -> None: ...
    def get_by_user(self, user_id: str) -> list[DeviceToken]: ...
    def get_all(self) -> list[DeviceToken]: ...
    def delete(self, token: str) -> None: ...
