from typing import Protocol, List, Tuple
from src.modules.aseguradora.domain.models.ajustador_model import AjustadorModel

class AjustadorRepositoryPort(Protocol):
    def save(self, ajustador: AjustadorModel) -> AjustadorModel: ...
    def get_by_id(self, id: str) -> AjustadorModel | None: ...
    def get_by_usuario_id(self, usuario_id: str) -> AjustadorModel | None: ...
    def list_by_aseguradora(self, aseguradora_id: str, offset: int = 0, limit: int = 20, activo_para_servicio: bool | None = None) -> Tuple[List[AjustadorModel], int]: ...
    def update(self, ajustador: AjustadorModel) -> AjustadorModel: ...
    def delete(self, id: str) -> None: ...
