from typing import Protocol, List, Tuple
from src.modules.aseguradora.domain.models.cliente_model import ClienteModel

class ClienteRepositoryPort(Protocol):
    def save(self, cliente: ClienteModel) -> ClienteModel: ...
    def get_by_id(self, id: str) -> ClienteModel | None: ...
    def get_by_usuario_id(self, usuario_id: str) -> ClienteModel | None: ...
    def list_by_aseguradora(self, aseguradora_id: str, offset: int = 0, limit: int = 20) -> Tuple[List[ClienteModel], int]: ...
    def update(self, cliente: ClienteModel) -> ClienteModel: ...
    def delete(self, id: str) -> None: ...
