from typing import Protocol, List, Tuple
from src.modules.aseguradora.domain.models.taller_model import TallerModel

class TallerRepositoryPort(Protocol):
    def save(self, taller: TallerModel) -> TallerModel: ...
    def get_by_id(self, id: str) -> TallerModel | None: ...
    def list_all(self, offset: int = 0, limit: int = 20) -> Tuple[List[TallerModel], int]: ...
    def list_by_aseguradora(self, aseguradora_id: str, offset: int = 0, limit: int = 20) -> Tuple[List[TallerModel], int]: ...
    def update(self, taller: TallerModel) -> TallerModel: ...
    def delete(self, id: str) -> None: ...
    def vincular_taller_aseguradora(self, taller_id: str, aseguradora_id: str) -> None: ...
    def desvincular_taller_aseguradora(self, taller_id: str, aseguradora_id: str) -> None: ...
