from typing import Protocol, Any

class UsuarioRepositoryPort(Protocol):
    def get_by_id(self, id: str) -> Any | None: ...
    def bloquear_por_arco(self, id: str) -> None: ...
    def desbloquear_por_arco(self, id: str) -> None: ...
