from typing import Protocol, List, Tuple
from src.modules.aseguradora.domain.models.vehiculo_model import VehiculoModel

class VehiculoRepositoryPort(Protocol):
    def save(self, vehiculo: VehiculoModel) -> VehiculoModel: ...
    def get_by_id(self, id: str) -> VehiculoModel | None: ...
    def list_by_aseguradora(self, aseguradora_id: str, offset: int = 0, limit: int = 20, cliente_id: str | None = None) -> Tuple[List[VehiculoModel], int]: ...
    def list_by_cliente(self, cliente_id: str, offset: int = 0, limit: int = 20) -> Tuple[List[VehiculoModel], int]: ...
    def update(self, vehiculo: VehiculoModel) -> VehiculoModel: ...
    def delete(self, id: str) -> None: ...
