from typing import Protocol, List, Tuple
from src.modules.siniestro.domain.models.siniestro_model import SiniestroModel

class SiniestroRepositoryPort(Protocol):
    def save(self, siniestro: SiniestroModel) -> SiniestroModel: ...
    def get_by_id(self, id: str) -> SiniestroModel | None: ...
    def list_by_aseguradora(self, aseguradora_id: str, offset: int = 0, limit: int = 20, estatus: str | None = None) -> Tuple[List[SiniestroModel], int]: ...
    def update(self, siniestro: SiniestroModel) -> SiniestroModel: ...
    def update_estatus(self, siniestro_id: str, estatus: str) -> SiniestroModel: ...
    def list_by_ajustador(self, ajustador_id: str, offset: int = 0, limit: int = 20, estatus: str | None = None) -> Tuple[List[SiniestroModel], int]: ...
