from typing import Protocol, List, Any
from src.modules.admin.domain.models import AseguradoraTenant, AuditLog

class AseguradoraRepositoryPort(Protocol):
    def save(self, aseguradora: AseguradoraTenant) -> AseguradoraTenant: ...
    def get_by_id(self, id: str) -> AseguradoraTenant | None: ...
    def list_all(self) -> List[AseguradoraTenant]: ...
    def update(self, aseguradora: AseguradoraTenant) -> AseguradoraTenant: ...

class AuditLogRepositoryPort(Protocol):
    def append(self, log: AuditLog) -> AuditLog: ...
    def list_logs(self) -> List[AuditLog]: ...
    def get_by_entity(self, entidad_afectada: str, entidad_id: str) -> List[AuditLog]: ...

class DesincorporacionJobPort(Protocol):
    def trigger_desincorporacion(self, aseguradora_id: str) -> None: ...

class AdminUserRepositoryPort(Protocol):
    def get_by_id(self, usuario_id: str) -> Any | None: ...
    def bloquear_por_arco(self, usuario_id: str) -> None: ...
    def block_all_users_from_tenant(self, tenant_id: str) -> None: ...
