from typing import Protocol, List, Any, Tuple
from src.modules.admin.domain.models import AseguradoraTenant, AuditLog

class AseguradoraRepositoryPort(Protocol):
    def save(self, aseguradora: AseguradoraTenant) -> AseguradoraTenant: ...
    def get_by_id(self, id: str) -> AseguradoraTenant | None: ...
    def list_all(self, offset: int = 0, limit: int = 20, include_deleted: bool = False) -> Tuple[List[AseguradoraTenant], int]: ...
    def update(self, aseguradora: AseguradoraTenant) -> AseguradoraTenant: ...

class AuditLogRepositoryPort(Protocol):
    def append(self, log: AuditLog) -> AuditLog: ...
    def list_logs(self, offset: int = 0, limit: int = 20, aseguradora_id: str | None = None) -> Tuple[List[AuditLog], int]: ...
    def get_by_entity(self, entidad_afectada: str) -> List[AuditLog]: ...

class DesincorporacionJobPort(Protocol):
    def trigger_desincorporacion(self, aseguradora_id: str) -> None: ...

class AdminUserRepositoryPort(Protocol):
    def get_by_id(self, usuario_id: str) -> Any | None: ...
    def bloquear_por_arco(self, usuario_id: str) -> None: ...
    def block_all_users_from_tenant(self, tenant_id: str) -> None: ...
    def list_all(self, offset: int = 0, limit: int = 20, rol: str | None = None, estatus: str | None = None, search: str | None = None) -> Tuple[List[Any], int]: ...
    def update_user(self, usuario_id: str, data: dict) -> Any | None: ...
    def soft_delete(self, usuario_id: str) -> bool: ...

class AdminPurgeRepositoryPort(Protocol):
    def purge_aseguradora(self, aseguradora_id: str) -> dict: ...
