from typing import Protocol, Optional
from src.modules.taller.domain.models.cotizacion_model import CotizacionTallerModel

class CotizacionRepositoryPort(Protocol):
    def save(self, cotizacion: CotizacionTallerModel) -> CotizacionTallerModel: ...
    def get_by_siniestro(self, siniestro_id: str) -> Optional[CotizacionTallerModel]: ...
    def get_by_id(self, id: str) -> Optional[CotizacionTallerModel]: ...
    def update_estatus(self, id: str, estatus: str) -> CotizacionTallerModel: ...
