from typing import Protocol, Optional

class PerfilTallerRepositoryPort(Protocol):
    def get_taller_id_by_usuario(self, usuario_id: str) -> Optional[str]: ...
    def add_usuario_a_taller(self, usuario_id: str, taller_id: str, puesto: str = "Operador") -> None: ...
