from typing import Protocol, Dict, Any
from src.modules.cliente.domain.models import ClienteProfile

class ClienteRepositoryPort(Protocol):
    def get_by_usuario_id(self, usuario_id: str) -> ClienteProfile | None: ...
    def save(self, profile: ClienteProfile) -> ClienteProfile: ...
    def update(self, profile: ClienteProfile) -> ClienteProfile: ...

class OcrPort(Protocol):
    async def extract_data(self, cedula_bytes: bytes, poliza_bytes: bytes) -> Dict[str, Any]: ...
